### PR TITLE
Fix for wrong date bug

### LINKED ISSUE #539: Getting wrong dates for request submission date
**What were you trying to achieve?**
See the date a candidate submitted a request.

**What are the expected results?**
See the correct date

**What are the received results?**
Saw a wrong date

**What are the steps to reproduce the issue?**
Submit a request for access and check the date the request was submitted in the candidates table

**In what environment did you encounter the issue?**
 This issue is platform independent

**Additional context**
- Getting the correct date from the API, but the Front-end application is displaying wrong date
- Suspected root cause is the formatDateString function called on [this line](https://github.com/airqo-platform/AirQo-frontend/blob/f344e11643e4a9434f915b36363c454afa1956c7/netmanager/src/views/pages/CandidateList/components/CandidatesTable/CandidatesTable.js#L214) 
image

### PR DESCRIPTION
**Pull request by 123MwanjeMike**
#### Summary of Changes (What does this PR do?)
- Fixed the `formatDateString` utility
- Closes #539 

#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Status of maturity (all need to be checked before merging):
- [x] I consider this code done
- [x] I've tested this locally
- [ ] This branch has been LGTM'ed by a reviewer

#### How should this be manually tested?
* Check the request submission dates on the candidates table.

#### What are the relevant tickets?
- [PLAT-1043](https://airqoteam.atlassian.net/browse/PLAT-1043?atlOrigin=eyJpIjoiYjhjN2IxMTFiMGJkNDc5MWE3YzY4MDFlYWEzNmY2OWYiLCJwIjoiaiJ9)
- #539 

#### Screenshots (optional)
image

### CODE REVIEW

File: netmanager/src/utils/dateTime.js [hunk 1]
```diff
@@ -2,14 +2,8 @@ import moment from "moment-timezone";
 
 export const formatDateString = (
   t,
-  format = "YYYY-MM-DD HH:mm",
-  tz = "Africa/Kampala"
-) => {
-  return moment
-    .utc(t, format)
-    .tz(tz || "Africa/Kampala")
```
Comment (123MwanjeMike) [inline netmanager/src/utils/dateTime.js:10]: The timezone function (`tz()`) was removed because it purpose is basically already achieved with the `.utc()` and `.format()` function combination. It was the root cause of the bug.

**Review by ja-odur — DISMISSED** [review]
I am see changes on the package-lock.json with no corresponding package installation/removal

**Comment by 123MwanjeMike** [comment]
> I am see changes on the package-lock.json with no corresponding package installation/removal

Thanks @ja-odur .
I did an `npm install` to regenerate the package-lock.json file. It ideally just updated the node modules and the lock file that's why there were not visible changes to the package.json file.

**Review by Codebmk — APPROVED** [review]

**Review by Baalmart — APPROVED** [review]
LGTM
